package com.github.yzqdev.pethome.datagen;


import com.github.yzqdev.pethome.server.item.PHItemRegistry;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;


public class ModEnLangProvider extends LanguageProvider {
    public ModEnLangProvider(PackOutput output, String modid, String locale) {
        super(output, modid, locale);
    }

    @Override
    protected void addTranslations() {
        add(LangDefinition.ITEM_GROUP, "Domestication Innovation");
        add(LangDefinition.ITEM_COLLAR_TAG, "Collar Tag");
        add(LangDefinition.ITEM_ROTTEN_APPLE, "Rotten Apple");
        add(LangDefinition.ITEM_SINISTER_CARROT, "Sinister Carrot");
        add(LangDefinition.ITEM_DEFLECTION_SHIELD, "Deflection Shield Model");
        add(LangDefinition.ITEM_MAGNET, "Magnet Model");
        add(LangDefinition.ITEM_FEATHER_ON_A_STICK, "Feather on a Stick");
        add(LangDefinition.ITEM_DEED_OF_OWNERSHIP, "Deed of Ownership");
        add(LangDefinition.ITEM_DEED_OF_OWNERSHIP_DESC, "Bound to %s");
        add(LangDefinition.ITEM_PET_COMPASS, "Pet Compass");
        add(LangDefinition.TOOLTIP_PET_COMPASS_DESC, "Right-click to open the pet list");
        add(LangDefinition.MESSAGE_PET_COMPASS_TITLE, "Pet Compass");
        add(LangDefinition.MESSAGE_PET_COMPASS_EMPTY, "No trackable pets yet");
        add(LangDefinition.MESSAGE_PET_COMPASS_POSITION, "Position: ");
        add(LangDefinition.MESSAGE_PET_COMPASS_LAST_KNOWN_POS, "Last known: ");
        add(LangDefinition.MESSAGE_PET_COMPASS_DISTANCE, "Dist: %s m");
        add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_LOADED, "Status: loaded");
        add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_NOT_LOADED, "Status: not loaded");
        add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_WRONG_DIM, "Status: in another dimension");
        add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_DEAD, "Status: dead, waiting for pet bed respawn");
        add(LangDefinition.MESSAGE_PET_COMPASS_BUTTON_TP, "Go to pet");
        add(LangDefinition.MESSAGE_PET_COMPASS_BUTTON_RECALL, "Recall");
        add(LangDefinition.MESSAGE_PET_COMPASS_DISABLED, "The pet compass is disabled in the config");
        add(LangDefinition.MESSAGE_PET_COMPASS_NOT_LOADED_CONFIRM, "Pet is not loaded, teleporting to its last known position");
        add(LangDefinition.MESSAGE_PET_COMPASS_DEAD_WAIT_RESPAWN, "This pet has died and is waiting to respawn at its pet bed");
        add(LangDefinition.MESSAGE_PET_COMPASS_RECALL_STARTED, "Searching for the pet, please wait...");
        add(LangDefinition.MESSAGE_PET_COMPASS_RECALL_FAILED, "Could not find the pet, please try again later");
        add(LangDefinition.MESSAGE_PET_COMPASS_TELEPORTED, "Teleported to your pet");
        add(LangDefinition.MESSAGE_PET_COMPASS_RECALLED, "%s has been recalled to you");
        add(LangDefinition.MESSAGE_PET_COMPASS_DIM_OVERWORLD, "Overworld");
        add(LangDefinition.MESSAGE_PET_COMPASS_DIM_THE_NETHER, "The Nether");
        add(LangDefinition.MESSAGE_PET_COMPASS_DIM_THE_END, "The End");
        // 物品/方块 tooltip（对齐 1.21.1 的 desc 提示行）
        add(LangDefinition.TOOLTIPS_SUBSTITUTE_COLLAR_DESC, "[Right-click on pets to put a collar on them]");
        add(LangDefinition.TOOLTIPS_SUBSTITUTE_FEATHER_DESC, "[Allows pets to move to the fishing rod landing point, e.g. moving pets to a pet bed]");
        add(LangDefinition.TOOLTIPS_SUBSTITUTE_PET_BED_DESC, "[Place pets on pet beds, pets will respawn the next day after death]");
        add(LangDefinition.TOOLTIPS_SUBSTITUTE_ROTTEN_APPLE_DESC, "[Feed to horses to turn them into zombie horses]");
        add(LangDefinition.TOOLTIPS_SUBSTITUTE_SINISTER_CARROT_DESC, "[Feed to a rabbit to turn it into a killer rabbit, feed to a zombie horse to turn it into a skeleton horse]");
        add(LangDefinition.TOOLTIPS_DRUM_DESC, "[Right-click to cycle the command for your pets within 32 blocks, can also be triggered by redstone]");
        add(LangDefinition.TOOLTIPS_WAYWARD_LANTERN_DESC, "[Place near you, pets that get unloaded far away will be teleported back to the lantern]");
        add(LangDefinition.BLOCK_PET_BED_WHITE, "White Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_ORANGE, "Orange Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_MAGENTA, "Magenta Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_LIGHT_BLUE, "Light Blue Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_YELLOW, "Yellow Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_LIME, "Lime Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_PINK, "Pink Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_GRAY, "Gray Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_LIGHT_GRAY, "Light Gray Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_CYAN, "Cyan Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_PURPLE, "Purple Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_BLUE, "Blue Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_BROWN, "Brown Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_GREEN, "Green Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_RED, "Red Pet Bed");
        add(LangDefinition.BLOCK_PET_BED_BLACK, "Black Pet Bed");
        add(LangDefinition.BLOCK_DRUM, "Command Drum");
        add(LangDefinition.BLOCK_WAYWARD_LANTERN, "Wayward Lantern");
        add(LangDefinition.MESSAGE_COMMAND_0, "%s is wandering");
        add(LangDefinition.MESSAGE_COMMAND_1, "%s is staying");
        add(LangDefinition.MESSAGE_COMMAND_2, "%s is following");
        add(LangDefinition.MESSAGE_DRUM_COMMAND_0, "ordered %s to wander");
        add(LangDefinition.MESSAGE_DRUM_COMMAND_1, "ordered %s to stay");
        add(LangDefinition.MESSAGE_DRUM_COMMAND_2, "ordered %s to follow");
        add(LangDefinition.MESSAGE_RESPAWN, "%s has respawned at its bed");
        add(LangDefinition.MESSAGE_REMOVE_RESPAWN, "Removed respawn bed of %s");
        add(LangDefinition.MESSAGE_GOODBYE, "%s will not respawn. Goodbye...");
        add(LangDefinition.MESSAGE_ENCHANTMENTS, "Enchantments:");
        add(LangDefinition.MESSAGE_ENCHANT_ERROR, "Enchanting error occurred, see latest.log");
        add(LangDefinition.MESSAGE_SET_OWNER, "%s is now the owner of %s");
        add(LangDefinition.MESSAGE_WAYWARD_LANTERN_RETURN, "%s has found its way to a nearby Wayward Lantern");
        add(LangDefinition.ENTITY_ANIMAL_TAMER, "Animal Tamer");
        add(LangDefinition.ENTITY_CHAIN_LIGHTNING, "Lightning");
        add(LangDefinition.ENTITY_RECALL_BALL, "Recall Orb");
        add(LangDefinition.ENTITY_FEATHER, "Feather");
        add(LangDefinition.ENTITY_FOLLOWING_JUKEBOX, "Floating Jukebox");
        add(LangDefinition.ENTITY_PSYCHIC_WALL, "Psychic Wall");
        add(LangDefinition.ENCHANT_HEALTH_BOOST, "Extra Health");
        add(LangDefinition.ENCHANT_HEALTH_BOOST_DESC, "Increases pet's max health by 10 for each level");
        add(LangDefinition.ENCHANT_FIREPROOF, "Fireproof");
        add(LangDefinition.ENCHANT_FIREPROOF_DESC, "Grants pet immunity to fire and lava damage");
        add(LangDefinition.ENCHANT_IMMUNITY_FRAME, "Immunity Frame");
        add(LangDefinition.ENCHANT_IMMUNITY_FRAME_DESC, "Each level makes pet immune for an additional second after attack");
        add(LangDefinition.ENCHANT_DEFLECTION, "Deflecting");
        add(LangDefinition.ENCHANT_DEFLECTION_DESC, "Pet is protected by a ghostly shield which deflects projectile attacks");
        add(LangDefinition.ENCHANT_POISON_RESISTANCE, "Poison Resistance");
        add(LangDefinition.ENCHANT_POISON_RESISTANCE_DESC, "Grants pet immunity to poison effect");
        add(LangDefinition.ENCHANT_CHAIN_LIGHTNING, "Chain Lightning");
        add(LangDefinition.ENCHANT_CHAIN_LIGHTNING_DESC, "Summons a lightning bolt that chains from and damages mobs each time a pet attacks, level increases how many mobs can be hit by lightning");
        add(LangDefinition.ENCHANT_SPEEDSTER, "Speedster");
        add(LangDefinition.ENCHANT_SPEEDSTER_DESC, "Increases pet's movement speed");
        add(LangDefinition.ENCHANT_FROST_FANG, "Frost Fang");
        add(LangDefinition.ENCHANT_FROST_FANG_DESC, "Pet attacks now slows mobs shortly and deals freezing damage");
        add(LangDefinition.ENCHANT_MAGNETIC, "Magnetic");
        add(LangDefinition.ENCHANT_MAGNETIC_DESC, "Pet aided by ghostly magnet that pulls targeted mobs towards it");
        add(LangDefinition.ENCHANT_LINKED_INVENTORY, "Linked Inventory");
        add(LangDefinition.ENCHANT_LINKED_INVENTORY_DESC, "Pet can pick up items and teleport them to owner's inventory");
        add(LangDefinition.ENCHANT_TOTAL_RECALL, "Total Recall");
        add(LangDefinition.ENCHANT_TOTAL_RECALL_DESC, "When below 2 health, pet enters a recall orb and is protected until released by its owner");
        add(LangDefinition.ENCHANT_HEALTH_SIPHON, "Health Siphon");
        add(LangDefinition.ENCHANT_HEALTH_SIPHON_DESC, "Any damage done to pet is transferred to its owner");
        add(LangDefinition.ENCHANT_BUBBLING, "Bubbling");
        add(LangDefinition.ENCHANT_BUBBLING_DESC, "Pet attacks trap mob inside giant bubble that floats upwards");
        add(LangDefinition.ENCHANT_HERDING, "Herding");
        add(LangDefinition.ENCHANT_HERDING_DESC, "Pet can be followed by wild animals, level increases maximum amount of followers");
        add(LangDefinition.ENCHANT_AMPHIBIOUS, "Amphibious");
        add(LangDefinition.ENCHANT_AMPHIBIOUS_DESC, "Pet cannot dry out or drown on land or in water, increases speed in water, pet will not float but swim quickly");
        add(LangDefinition.ENCHANT_VAMPIRE, "Vampire's Familiar");
        add(LangDefinition.ENCHANT_VAMPIRE_DESC, "Pet heals amount of damage done, level increases percentage of dealt damage healed");
        add(LangDefinition.ENCHANT_VOID_CLOUD, "Void Cloud");
        add(LangDefinition.ENCHANT_VOID_CLOUD_DESC, "Pet is protected from falling off cliffs or into void by a large cloud that lifts it up and returns it to its owner");
        add(LangDefinition.ENCHANT_CHARISMA, "Charismatic");
        add(LangDefinition.ENCHANT_CHARISMA_DESC, "Pet lowers trade prices for its owner, level increases the bargain");
        add(LangDefinition.ENCHANT_UNDEAD_CURSE, "Curse of Afterlife");
        add(LangDefinition.ENCHANT_UNDEAD_CURSE_DESC, "Pet returns as a hostile, zombie pet after death");
        add(LangDefinition.ENCHANT_INFAMY_CURSE, "Curse of Infamy");
        add(LangDefinition.ENCHANT_INFAMY_CURSE_DESC, "Pet can naturally make any nearby monster hostile to it");
        add(LangDefinition.ENCHANT_SHADOW_HANDS, "Shadow Hands");
        add(LangDefinition.ENCHANT_SHADOW_HANDS_DESC, "Pet uses dark magic to attack targets with shadowy hands, level increases speed and amount of hands");
        add(LangDefinition.ENCHANT_DISC_JOCKEY, "Disc Jockey");
        add(LangDefinition.ENCHANT_DISC_JOCKEY_DESC, "Pet is followed by a floating jukebox that can play music discs");
        add(LangDefinition.ENCHANT_DEFUSAL, "Defusal");
        add(LangDefinition.ENCHANT_DEFUSAL_DESC, "Pet can nullify explosion damage to terrain and other mobs, level increases range");
        add(LangDefinition.ENCHANT_WARPING_BITE, "Warping Bite");
        add(LangDefinition.ENCHANT_WARPING_BITE_DESC, "Pet will randomly teleport targeted mobs away from it");
        add(LangDefinition.ENCHANT_ORE_SCENTING, "Ore Scenting");
        add(LangDefinition.ENCHANT_ORE_SCENTING_DESC, "Pet can sniff out ore blocks and alert its owner, level determines distance, amount and frequency of ore detection");
        add(LangDefinition.ENCHANT_GLUTTONOUS, "Gluttonous");
        add(LangDefinition.ENCHANT_GLUTTONOUS_DESC, "Pet can eat any food item, regardless of dietary restrictions");
        add(LangDefinition.ENCHANT_PSYCHIC_WALL, "Psychic Wall");
        add(LangDefinition.ENCHANT_PSYCHIC_WALL_DESC, "Pet summons a wall of psychic energy during combat to provide cover, level determines size of wall and length of the effect");
        add(LangDefinition.ENCHANT_INTIMIDATION, "Intimidation");
        add(LangDefinition.ENCHANT_INTIMIDATION_DESC, "Pet can scare away hostile mobs with its fearsome appearance, level determines range and frequency of effect");
        add(LangDefinition.ENCHANT_BLIGHT_CURSE, "Curse of Blight");
        add(LangDefinition.ENCHANT_BLIGHT_CURSE_DESC, "Plants will wither and die around the pet.");
        add(LangDefinition.ENCHANT_TETHERED_TELEPORT, "Tethered Teleport");
        add(LangDefinition.ENCHANT_TETHERED_TELEPORT_DESC, "Pet will teleport with its owner, even across dimensions.");
        add(LangDefinition.ENCHANT_IMMATURITY_CURSE, "Curse of Immaturity");
        add(LangDefinition.ENCHANT_IMMATURITY_CURSE_DESC, "Pet appears and behaves as a baby version of itself, with reduced attack damage.");
        add(LangDefinition.ENCHANT_MUFFLED, "Muffled");
        add(LangDefinition.ENCHANT_MUFFLED_DESC, "Pet will be silent and not emit vibrations when moving.");
        add(LangDefinition.ENCHANT_BLAZING_PROTECTION, "Blazing Protection");
        add(LangDefinition.ENCHANT_BLAZING_PROTECTION_DESC, "Pet will be protected from damage by 2 blazing bars per level, which knockback and set attackers on fire.");
        add(LangDefinition.ENCHANT_HEALING_AURA, "Healing Aura");
        add(LangDefinition.ENCHANT_HEALING_AURA_DESC, "Pet will ocassionally heal owner and other pets around it, level determines strength of healing effect.");
        add(LangDefinition.ENCHANT_REJUVENATION, "Rejuvenation");
        add(LangDefinition.ENCHANT_REJUVENATION_DESC, "When injured, pet may absorb experience orbs to heal itself.");
        add(LangDefinition.ENCHANT_XP_TRANSFER, "XP Transfer");
        add(LangDefinition.ENCHANT_XP_TRANSFER_DESC, "Pets collect and transfer XP to owner");
        add(LangDefinition.EFFECT_DRUNK, "Chaos");
        add(LangDefinition.ENCHANT_INSIGHT, "Insight");
        add(LangDefinition.ENCHANT_INSIGHT_DESC, "In dark areas, pets highlight surrounding hostile mobs");
        add(LangDefinition.ENCHANT_CHAOS, "Chaos Mind");
        add(LangDefinition.ENCHANT_CHAOS_DESC, "When attacked, pets inflict Chaos on the attacker, forcing them to attack other monsters within 10 blocks");
        add(LangDefinition.ENCHANT_SHARE, "Share");
        add(LangDefinition.ENCHANT_SHARE_DESC, "When the pet is attacked, it shares damage with nearby hostile mobs");
        add(LangDefinition.ENCHANT_NIGHT_VISION, "Night Vision");
        add(LangDefinition.ENCHANT_NIGHT_VISION_DESC, "Grants Night Vision effect when a pet is nearby");
        add(LangDefinition.ENCHANT_PARALYSIS, "Paralysis");
        add(LangDefinition.ENCHANT_PARALYSIS_DESC, "When attacked, pets paralyze the attacker for several seconds, preventing movement, jumping or attacking");
        add(LangDefinition.ENCHANT_TOUGH, "Tough");
        add(LangDefinition.ENCHANT_TOUGH_DESC, "Increase pet defense and knockback resistance");
        add(LangDefinition.ENCHANT_VIOLENT, "Violent");
        add(LangDefinition.ENCHANT_VIOLENT_DESC, "Monster will get some debuffs when attacked by pet");
        add(LangDefinition.ENCHANT_SONIC_BOOM, "Sonic Boom");
        add(LangDefinition.ENCHANT_SONIC_BOOM_DESC, "Sonic boom knocks enemies back, triggered periodically");
        add(LangDefinition.SOUND_SUBTITLE_COLLAR_TAG, "equipped Collar Tag");
        add(LangDefinition.SOUND_SUBTITLE_MAGNET_LOOP, "Magnet buzzes");
        add(LangDefinition.SOUND_SUBTITLE_CHAIN_LIGHTNING, "Lightning zaps");
        add(LangDefinition.SOUND_SUBTITLE_GIANT_BUBBLE_INFLATE, "Giant Bubble inflates");
        add(LangDefinition.SOUND_SUBTITLE_GIANT_BUBBLE_POP, "Giant Bubble pops");
        add(LangDefinition.SOUND_SUBTITLE_PET_BED_USES, "Pet Bed adjusted");
        add(LangDefinition.SOUND_SUBTITLE_DRUM, "Command Drum beats");
        add(LangDefinition.SOUND_SUBTITLE_PSYCHIC_WALL, "Psychic Wall hums");
        add(LangDefinition.SOUND_SUBTITLE_PSYCHIC_WALL_DEFLECT, "Psychic Wall deflects");
        add(LangDefinition.SOUND_SUBTITLE_BLAZING_PROTECTION, "Blazing bar dissapears");
        add(LangDefinition.NOTIF_FRIENDLY_FIRE_PROTECTED, "The %s is protected. Crouch to bypass.");
        add(LangDefinition.JADE_COLLAR_TAG, "Show collar tag enchantment");

        add(LangDefinition.has_pet_bed_at_pos, "Bound pet bed at (%s)");
        add(PHItemRegistry.NET_LAUNCHER_ITEM.get(), "Creature Capture Launcher");
        add(PHItemRegistry.NET_ITEM.get(), "Capture Ball");
        add(PHItemRegistry.NET_HAS_ITEM.get(), "Capture Ball (Occupied)");
        add(LangDefinition.capturing_text, "Capturing");
        add(LangDefinition.release_text, "Release");
        add(LangDefinition.health_text, "Health");
        add(LangDefinition.no_net_entity_text, "No creature available to release");
        add(LangDefinition.net_launcher_tip, "[Hold Shift + Right Click to toggle between Capture and Release modes]");
        add(LangDefinition.net_launcher_default_only_tamable, "By default, only tamable mobs can be captured (configurable in settings file).");
        add(LangDefinition.mobcatcherOnlyTamableAnimal_conf, "Only tamable mobs can be captured");
        add(LangDefinition.mobcatcherOnlyTamableAnimal_conf_tooltip, "Disable to allow capturing any mob");
        add(LangDefinition.mobcatcherBlacklist_conf, "Mob Catcher prohibited list");
        add(LangDefinition.mobcatcherBlacklist_conf_tooltip, "Mobs that are blocked from being captured");
        add(LangDefinition.share_loot_chance_conf, "Share Enchantment Chance");
        add(LangDefinition.share_loot_chance_conf_tooltip, "Probability of Share enchantment book appearing in End City chests");
        add(LangDefinition.sonic_boom_loot_chance_conf, "Sonic Boom Enchantment Chance");
        add(LangDefinition.sonic_boom_loot_chance_conf_tooltip, "Probability of Sonic Boom enchantment book appearing in Ancient City chests");
        add(LangDefinition.paralysis_loot_chance_conf, "Paralysis Enchantment Chance");
        add(LangDefinition.paralysis_loot_chance_conf_tooltip, "Probability of Paralysis enchantment book appearing in Abandoned Mineshaft chests, Desert Temple chests, Fishing loot");
        add(LangDefinition.tough_loot_chance_conf, "Tough Enchantment Chance");
        add(LangDefinition.tough_loot_chance_conf_tooltip, "Probability of Tough enchantment book appearing in Abandoned Mineshaft chests");

        // ===== 1.20.1 专属设置界面（PetHomeConfigScreen）=====
        add(LangDefinition.GUI_TITLE, "Pet Home · Settings");
        add(LangDefinition.GUI_SUBTITLE, "Changes save instantly to config/pet_home.toml");
        add(LangDefinition.GUI_ON, "ON");
        add(LangDefinition.GUI_OFF, "OFF");
        add(LangDefinition.GUI_RESET, "Reset");
        add(LangDefinition.GUI_CAT_FRIENDLY_NAME, "Friendly Fire");
        add(LangDefinition.GUI_CAT_FRIENDLY_DESC, "Protection rules for pets, owners and teams");
        add(LangDefinition.GUI_CAT_GENERAL_NAME, "General");
        add(LangDefinition.GUI_CAT_GENERAL_DESC, "Toggles for pet beds, commands, mob catcher, etc.");
        add(LangDefinition.GUI_CAT_TAMEABLE_NAME, "Extra Tameables");
        add(LangDefinition.GUI_CAT_TAMEABLE_DESC, "Taming toggles for axolotl, fox, frog, horse and rabbit");
        add(LangDefinition.GUI_CAT_LOOT_NAME, "Loot Chances");
        add(LangDefinition.GUI_CAT_LOOT_DESC, "Chest loot chances for enchanted books and special items");
        add(LangDefinition.GUI_CAT_ENCHANTS_NAME, "Enchantment Toggles");
        add(LangDefinition.GUI_CAT_ENCHANTS_DESC, "Enable or disable each pet enchantment");
        add(LangDefinition.GUI_F_PROTECT_OWNER, "Owner cannot hurt their pets");
        add(LangDefinition.GUI_F_PROTECT_OWNER_DESC, "Attacks from the owner on their own pets are void");
        add(LangDefinition.GUI_F_PROTECT_PETS, "Pets cannot hurt each other");
        add(LangDefinition.GUI_F_PROTECT_PETS_DESC, "Pets attacking other players pets is void");
        add(LangDefinition.GUI_F_PROTECT_CHILDREN, "Protect baby animals");
        add(LangDefinition.GUI_F_PROTECT_CHILDREN_DESC, "Baby animals are protected");
        add(LangDefinition.GUI_F_REFLECT_DAMAGE, "Reflect damage");
        add(LangDefinition.GUI_F_REFLECT_DAMAGE_DESC, "Damage is reflected back to the attacker when protection triggers");
        add(LangDefinition.GUI_F_DISPLAY_WARNING, "Show protection warning");
        add(LangDefinition.GUI_F_DISPLAY_WARNING_DESC, "Shows a message when attacking a protected pet");
        add(LangDefinition.GUI_F_PROTECT_TEAM, "Protect team members");
        add(LangDefinition.GUI_F_PROTECT_TEAM_DESC, "Mobs on the same team protect each other");
        add(LangDefinition.GUI_F_RESPECT_TEAM, "Respect team rules");
        add(LangDefinition.GUI_F_RESPECT_TEAM_DESC, "Protection follows vanilla team rules");
        add(LangDefinition.GUI_F_CAN_HURT_PET_ITEMS, "Items that can hurt pets");
        add(LangDefinition.GUI_F_CAN_HURT_PET_ITEMS_DESC, "Comma-separated item IDs; holding these allows hurting pets (e.g. minecraft:egg)");
        add(LangDefinition.GUI_F_CAN_HURT_ALL_ITEMS, "Items that always hurt");
        add(LangDefinition.GUI_F_CAN_HURT_ALL_ITEMS_DESC, "Comma-separated item IDs; holding these bypasses protection");
        add(LangDefinition.GUI_F_NO_PROTECTION, "Unprotected mobs");
        add(LangDefinition.GUI_F_NO_PROTECTION_DESC, "Comma-separated entity IDs exempt from protection rules");
        add(LangDefinition.GUI_F_EXTRA_PROTECTED, "Extra protected mobs");
        add(LangDefinition.GUI_F_EXTRA_PROTECTED_DESC, "Comma-separated entity IDs also covered by protection");
        add(LangDefinition.GUI_F_PLAYER_PROTECTED, "Mobs players cannot hurt");
        add(LangDefinition.GUI_F_PLAYER_PROTECTED_DESC, "Comma-separated entity IDs that players cannot hurt");
        add(LangDefinition.GUI_G_ROTTEN_APPLE, "Rotten apple conversion");
        add(LangDefinition.GUI_G_ROTTEN_APPLE_DESC, "Dropped apples rot into rotten apples");
        add(LangDefinition.GUI_G_PET_BED_RESPAWN, "Pet bed respawn");
        add(LangDefinition.GUI_G_PET_BED_RESPAWN_DESC, "Pets respawn at their bound pet bed the next morning");
        add(LangDefinition.GUI_G_RABBITS_RAVAGERS, "Rabbits scare ravagers");
        add(LangDefinition.GUI_G_RABBITS_RAVAGERS_DESC, "Restores the legacy behavior: ravagers fear rabbits");
        add(LangDefinition.GUI_G_TRINARY_COMMAND, "Trinary command system");
        add(LangDefinition.GUI_G_TRINARY_COMMAND_DESC, "Right-click pets to cycle wander/stay/follow");
        add(LangDefinition.GUI_G_ANIMAL_TAMER, "Animal tamer villager");
        add(LangDefinition.GUI_G_ANIMAL_TAMER_DESC, "Enables the animal tamer profession and pet shop structure");
        add(LangDefinition.GUI_G_PETSTORE_WEIGHT, "Pet store spawn weight");
        add(LangDefinition.GUI_G_PETSTORE_WEIGHT_DESC, "Spawn weight of pet stores in villages (0 disables)");
        add(LangDefinition.GUI_G_MOB_TAMABLE_ONLY, "Mob catcher: tameable only");
        add(LangDefinition.GUI_G_MOB_TAMABLE_ONLY_DESC, "If disabled, the mob catcher can capture any mob");
        add(LangDefinition.GUI_G_MOB_BLACKLIST, "Mob catcher blacklist");
        add(LangDefinition.GUI_G_MOB_BLACKLIST_DESC, "Comma-separated entity IDs that cannot be captured");
        add(LangDefinition.GUI_G_PET_COMPASS_ENABLE, "Pet Compass");
        add(LangDefinition.GUI_G_PET_COMPASS_ENABLE_DESC, "Whether to enable the pet compass system");
        add(LangDefinition.GUI_G_TELEPORT_PLAYER_TO_PET, "Teleport Player to Pet");
        add(LangDefinition.GUI_G_TELEPORT_PLAYER_TO_PET_DESC, "Whether to allow teleporting the player to the pet");
        add(LangDefinition.GUI_G_RECALL_PET_TO_PLAYER, "Recall Pet");
        add(LangDefinition.GUI_G_RECALL_PET_TO_PLAYER_DESC, "Whether to allow recalling (teleporting) the pet to the player");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY, "Pet Info Panel");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY_DESC, "Show the pet info panel at the top of the screen while looking at your own pet");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY_REQUIRE_SHIFT, "Require Sneak");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY_REQUIRE_SHIFT_DESC, "Show the panel only while sneaking and looking at the pet (when off, just look at the pet)");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY_IGNORE_JADE, "Show Even with Jade");
        add(LangDefinition.GUI_G_PET_INFO_OVERLAY_IGNORE_JADE_DESC, "Show the panel even when Jade is installed (Jade's tooltip already shows pet info)");
        add(LangDefinition.GUI_T_AXOLOTL, "Tameable axolotls");
        add(LangDefinition.GUI_T_AXOLOTL_DESC, "Axolotls can be tamed with tropical fish");
        add(LangDefinition.GUI_T_FOX, "Tameable foxes");
        add(LangDefinition.GUI_T_FOX_DESC, "Foxes can be tamed with sweet berries");
        add(LangDefinition.GUI_T_FROG, "Tameable frogs");
        add(LangDefinition.GUI_T_FROG_DESC, "Frogs can be tamed with spider eyes");
        add(LangDefinition.GUI_T_HORSE, "Tameable horses");
        add(LangDefinition.GUI_T_HORSE_DESC, "Horses can be tamed like wolves");
        add(LangDefinition.GUI_T_RABBIT, "Tameable rabbits");
        add(LangDefinition.GUI_T_RABBIT_DESC, "Rabbits can be tamed with carrots");
        add(LangDefinition.GUI_L_CURSE_LOOT_ONLY, "Curse enchants loot-only");
        add(LangDefinition.GUI_L_CURSE_LOOT_ONLY_DESC, "Curse enchantments only appear in chests");
        add(LangDefinition.GUI_L_SINISTER_CARROT_DESC, "Chance of sinister carrots in woodland mansion chests");
        add(LangDefinition.GUI_L_BUBBLING_DESC, "Chance of Bubbling books in buried treasure");
        add(LangDefinition.GUI_L_VAMPIRISM_DESC, "Chance of Vampire books in woodland mansions");
        add(LangDefinition.GUI_L_VOID_CLOUD_DESC, "Chance of Void Cloud books in end cities");
        add(LangDefinition.GUI_L_ORE_SCENTING_DESC, "Chance of Ore Scenting books in mineshafts");
        add(LangDefinition.GUI_L_MUFFLED_DESC, "Chance of Muffled books in ancient cities");
        add(LangDefinition.GUI_L_BLAZING_DESC, "Chance of Blazing Protection books in nether fortresses");
        add(LangDefinition.GUI_L_SHARE_DESC, "Chance of Share books in end cities");
        add(LangDefinition.GUI_L_SONIC_BOOM_DESC, "Chance of Sonic Boom books in woodland mansions");
        add(LangDefinition.GUI_L_PARALYSIS_DESC, "Chance of Paralysis books in mineshafts, desert pyramids and bonus chests");
        add(LangDefinition.GUI_L_TOUGH_DESC, "Chance of Tough books in abandoned mineshafts");
    }
}
