package com.github.yzqdev.pethome.datagen;


import com.github.yzqdev.pethome.server.item.PHItemRegistry;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;


public class ModEnLangProvider extends LanguageProvider {
    public ModEnLangProvider(PackOutput output, String modid, String locale) {
        super(output, modid, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.pet_home", "Domestication Innovation");
        add("item.pet_home.collar_tag", "Collar Tag");
        add("item.pet_home.rotten_apple", "Rotten Apple");
        add("item.pet_home.sinister_carrot", "Sinister Carrot");
        add("item.pet_home.deflection_shield", "Deflection Shield Model");
        add("item.pet_home.magnet", "Magnet Model");
        add("item.pet_home.feather_on_a_stick", "Feather on a Stick");
        add("item.pet_home.deed_of_ownership", "Deed of Ownership");
        add("item.pet_home.deed_of_ownership.desc", "Bound to %s");
        add("block.pet_home.pet_bed_white", "White Pet Bed");
        add("block.pet_home.pet_bed_orange", "Orange Pet Bed");
        add("block.pet_home.pet_bed_magenta", "Magenta Pet Bed");
        add("block.pet_home.pet_bed_light_blue", "Light Blue Pet Bed");
        add("block.pet_home.pet_bed_yellow", "Yellow Pet Bed");
        add("block.pet_home.pet_bed_lime", "Lime Pet Bed");
        add("block.pet_home.pet_bed_pink", "Pink Pet Bed");
        add("block.pet_home.pet_bed_gray", "Gray Pet Bed");
        add("block.pet_home.pet_bed_light_gray", "Light Gray Pet Bed");
        add("block.pet_home.pet_bed_cyan", "Cyan Pet Bed");
        add("block.pet_home.pet_bed_purple", "Purple Pet Bed");
        add("block.pet_home.pet_bed_blue", "Blue Pet Bed");
        add("block.pet_home.pet_bed_brown", "Brown Pet Bed");
        add("block.pet_home.pet_bed_green", "Green Pet Bed");
        add("block.pet_home.pet_bed_red", "Red Pet Bed");
        add("block.pet_home.pet_bed_black", "Black Pet Bed");
        add("block.pet_home.drum", "Command Drum");
        add("block.pet_home.wayward_lantern", "Wayward Lantern");
        add("message.pet_home.command_0", "%s is wandering");
        add("message.pet_home.command_1", "%s is staying");
        add("message.pet_home.command_2", "%s is following");
        add("message.pet_home.drum_command_0", "ordered %s to wander");
        add("message.pet_home.drum_command_1", "ordered %s to stay");
        add("message.pet_home.drum_command_2", "ordered %s to follow");
        add("message.pet_home.respawn", "%s has respawned at its bed");
        add("message.pet_home.remove_respawn", "Removed respawn bed of %s");
        add("message.pet_home.goodbye", "%s will not respawn. Goodbye...");
        add("message.pet_home.enchantments", "Enchantments:");
        add("message.pet_home.set_owner", "%s is now the owner of %s");
        add("message.pet_home.wayward_lantern_return", "%s has found its way to a nearby Wayward Lantern");
        add("entity.minecraft.villager.pet_home.animal_tamer", "Animal Tamer");
        add("entity.pet_home.chain_lightning", "Lightning");
        add("entity.pet_home.recall_ball", "Recall Orb");
        add("entity.pet_home.feather", "Feather");
        add("entity.pet_home.following_jukebox", "Floating Jukebox");
        add("entity.pet_home.psychic_wall", "Psychic Wall");
        add("enchantment.pet_home.health_boost", "Extra Health");
        add("enchantment.pet_home.health_boost.desc", "Increases pet's max health by 10 for each level");
        add("enchantment.pet_home.fireproof", "Fireproof");
        add("enchantment.pet_home.fireproof.desc", "Grants pet immunity to fire and lava damage");
        add("enchantment.pet_home.immunity_frame", "Immunity Frame");
        add("enchantment.pet_home.immunity_frame.desc", "Each level makes pet immune for an additional second after attack");
        add("enchantment.pet_home.deflection", "Deflecting");
        add("enchantment.pet_home.deflection.desc", "Pet is protected by a ghostly shield which deflects projectile attacks");
        add("enchantment.pet_home.poison_resistance", "Poison Resistance");
        add("enchantment.pet_home.poison_resistance.desc", "Grants pet immunity to poison effect");
        add("enchantment.pet_home.chain_lightning", "Chain Lightning");
        add("enchantment.pet_home.chain_lightning.desc", "Summons a lightning bolt that chains from and damages mobs each time a pet attacks, level increases how many mobs can be hit by lightning");
        add("enchantment.pet_home.speedster", "Speedster");
        add("enchantment.pet_home.speedster.desc", "Increases pet's movement speed");
        add("enchantment.pet_home.frost_fang", "Frost Fang");
        add("enchantment.pet_home.frost_fang.desc", "Pet attacks now slows mobs shortly and deals freezing damage");
        add("enchantment.pet_home.magnetic", "Magnetic");
        add("enchantment.pet_home.magnetic.desc", "Pet aided by ghostly magnet that pulls targeted mobs towards it");
        add("enchantment.pet_home.linked_inventory", "Linked Inventory");
        add("enchantment.pet_home.linked_inventory.desc", "Pet can pick up items and teleport them to owner's inventory");
        add("enchantment.pet_home.total_recall", "Total Recall");
        add("enchantment.pet_home.total_recall.desc", "When below 2 health, pet enters a recall orb and is protected until released by its owner");
        add("enchantment.pet_home.health_siphon", "Health Siphon");
        add("enchantment.pet_home.health_siphon.desc", "Any damage done to pet is transferred to its owner");
        add("enchantment.pet_home.bubbling", "Bubbling");
        add("enchantment.pet_home.bubbling.desc", "Pet attacks trap mob inside giant bubble that floats upwards");
        add("enchantment.pet_home.herding", "Herding");
        add("enchantment.pet_home.herding.desc", "Pet can be followed by wild animals, level increases maximum amount of followers");
        add("enchantment.pet_home.amphibious", "Amphibious");
        add("enchantment.pet_home.amphibious.desc", "Pet cannot dry out or drown on land or in water, increases speed in water, pet will not float but swim quickly");
        add("enchantment.pet_home.vampire", "Vampire's Familiar");
        add("enchantment.pet_home.vampire.desc", "Pet heals amount of damage done, level increases percentage of dealt damage healed");
        add("enchantment.pet_home.void_cloud", "Void Cloud");
        add("enchantment.pet_home.void_cloud.desc", "Pet is protected from falling off cliffs or into void by a large cloud that lifts it up and returns it to its owner");
        add("enchantment.pet_home.charisma", "Charismatic");
        add("enchantment.pet_home.charisma.desc", "Pet lowers trade prices for its owner, level increases the bargain");
        add("enchantment.pet_home.undead_curse", "Curse of Afterlife");
        add("enchantment.pet_home.undead_curse.desc", "Pet returns as a hostile, zombie pet after death");
        add("enchantment.pet_home.infamy_curse", "Curse of Infamy");
        add("enchantment.pet_home.infamy_curse.desc", "Pet can naturally make any nearby monster hostile to it");
        add("enchantment.pet_home.shadow_hands", "Shadow Hands");
        add("enchantment.pet_home.shadow_hands.desc", "Pet uses dark magic to attack targets with shadowy hands, level increases speed and amount of hands");
        add("enchantment.pet_home.disc_jockey", "Disc Jockey");
        add("enchantment.pet_home.disc_jockey.desc", "Pet is followed by a floating jukebox that can play music discs");
        add("enchantment.pet_home.defusal", "Defusal");
        add("enchantment.pet_home.defusal.desc", "Pet can nullify explosion damage to terrain and other mobs, level increases range");
        add("enchantment.pet_home.warping_bite", "Warping Bite");
        add("enchantment.pet_home.warping_bite.desc", "Pet will randomly teleport targeted mobs away from it");
        add("enchantment.pet_home.ore_scenting", "Ore Scenting");
        add("enchantment.pet_home.ore_scenting.desc", "Pet can sniff out ore blocks and alert its owner, level determines distance, amount and frequency of ore detection");
        add("enchantment.pet_home.gluttonous", "Gluttonous");
        add("enchantment.pet_home.gluttonous.desc", "Pet can eat any food item, regardless of dietary restrictions");
        add("enchantment.pet_home.psychic_wall", "Psychic Wall");
        add("enchantment.pet_home.psychic_wall.desc", "Pet summons a wall of psychic energy during combat to provide cover, level determines size of wall and length of the effect");
        add("enchantment.pet_home.intimidation", "Intimidation");
        add("enchantment.pet_home.intimidation.desc", "Pet can scare away hostile mobs with its fearsome appearance, level determines range and frequency of effect");
        add("enchantment.pet_home.blight_curse", "Curse of Blight");
        add("enchantment.pet_home.blight_curse.desc", "Plants will wither and die around the pet.");
        add("enchantment.pet_home.tethered_teleport", "Tethered Teleport");
        add("enchantment.pet_home.tethered_teleport.desc", "Pet will teleport with its owner, even across dimensions.");
        add("enchantment.pet_home.immaturity_curse", "Curse of Immaturity");
        add("enchantment.pet_home.immaturity_curse.desc", "Pet appears and behaves as a baby version of itself, with reduced attack damage.");
        add("enchantment.pet_home.muffled", "Muffled");
        add("enchantment.pet_home.muffled.desc", "Pet will be silent and not emit vibrations when moving.");
        add("enchantment.pet_home.blazing_protection", "Blazing Protection");
        add("enchantment.pet_home.blazing_protection.desc", "Pet will be protected from damage by 2 blazing bars per level, which knockback and set attackers on fire.");
        add("enchantment.pet_home.healing_aura", "Healing Aura");
        add("enchantment.pet_home.healing_aura.desc", "Pet will ocassionally heal owner and other pets around it, level determines strength of healing effect.");
        add("enchantment.pet_home.rejuvenation", "Rejuvenation");
        add("enchantment.pet_home.rejuvenation.desc", "When injured, pet may absorb experience orbs to heal itself.");
        add("pet_home.sound.subtitle.collar_tag", "equipped Collar Tag");
        add("pet_home.sound.subtitle.magnet_loop", "Magnet buzzes");
        add("pet_home.sound.subtitle.chain_lightning", "Lightning zaps");
        add("pet_home.sound.subtitle.giant_bubble_inflate", "Giant Bubble inflates");
        add("pet_home.sound.subtitle.giant_bubble_pop", "Giant Bubble pops");
        add("pet_home.sound.subtitle.pet_bed_uses", "Pet Bed adjusted");
        add("pet_home.sound.subtitle.drum", "Command Drum beats");
        add("pet_home.sound.subtitle.psychic_wall", "Psychic Wall hums");
        add("pet_home.sound.subtitle.psychic_wall_deflect", "Psychic Wall deflects");
        add("pet_home.sound.subtitle.blazing_protection", "Blazing bar dissapears");
        add("notif.friendlyfire.protected", "The %s is protected. Crouch to bypass.");
        add("config.jade.plugin_pet_home.collar_tag", "Show collar tag enchantment");

        add(LangDefinition.ConstantMsg.has_pet_bed_at_pos, "has petbed at ( %s )");
        add(PHItemRegistry.NET_LAUNCHER_ITEM.get(), "Creature Capture Launcher");
        add(PHItemRegistry.NET_ITEM.get(), "Capture Ball");
        add(PHItemRegistry.NET_HAS_ITEM.get(), "Capture Ball (Occupied)");
        add(LangDefinition.ConstantMsg.capturing_text, "Capturing");
        add(LangDefinition.ConstantMsg.release_text, "Release");
        add(LangDefinition.ConstantMsg.health_text, "Health");
        add(LangDefinition.ConstantMsg.no_net_entity_text, "No creature available to release");
        add(LangDefinition.ConstantMsg.net_launcher_tip, "[Hold Shift + Right Click to toggle between Capture and Release modes]");
        add(LangDefinition.ConstantMsg.net_launcher_default_only_tamable, "By default, only tamable mobs can be captured (configurable in settings file).");
        add(LangDefinition.conf("mobcatcherOnlyTamableAnimal"), "Only tamable mobs can be captured");
        add(LangDefinition.conf("mobcatcherOnlyTamableAnimal.tooltip"), "Disable to allow capturing any mob");
        add(LangDefinition.conf("mobcatcherBlacklist"), "Mob Catcher prohibited list");
        add(LangDefinition.conf("mobcatcherBlacklist.tooltip"), "Mobs that are blocked from being captured");
    }
}
