package com.github.yzqdev.pethome.datagen;

import com.github.yzqdev.pethome.server.item.PHItemRegistry;
import net.minecraft.resources.ResourceKey;
import java.util.concurrent.CompletableFuture;
import net.minecraft.world.item.enchantment.Enchantment;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class ModZhLangProvider extends FabricLanguageProvider {
    public ModZhLangProvider(FabricDataOutput output, CompletableFuture<net.minecraft.core.HolderLookup.Provider> registries) {
        super(output, "zh_cn", registries);
    }

    @Override
    public void generateTranslations(net.minecraft.core.HolderLookup.Provider registryLookup, TranslationBuilder builder) {
        builder.add(LangDefinition.TOOLTIP_SUBSTITUTE_FEATHER_DESC, "[可以让宠物移动到钓竿落点,比如把宠物移动到宠物床]");
        builder.add(LangDefinition.TOOLTIP_SUBSTITUTE_ROTTEN_APPLE_DESC, "[喂给马使其变为僵尸马]");
        builder.add(LangDefinition.TOOLTIP_SUBSTITUTE_SINISTER_CARROT_DESC, "[喂给兔子可将其转化为杀手兔,喂给僵尸马可将其转化为骷髅马]");
        builder.add(LangDefinition.TOOLTIP_SUBSTITUTE_COLLAR_DESC, "[右击宠物佩戴项圈]");
        builder.add(LangDefinition.TOOLTIP_SUBSTITUTE_PET_BED_DESC, "[将宠物放在宠物床上,宠物死亡会在第二天复活]");
        builder.add(LangDefinition.ITEM_GROUP, "驯养革新 | 物品");
        builder.add(LangDefinition.ITEM_COLLAR_TAG, "项圈标签");
        builder.add(LangDefinition.ITEM_ROTTEN_APPLE, "烂苹果");
        builder.add(LangDefinition.ITEM_SINISTER_CARROT, "阴恶胡萝卜");
        builder.add(LangDefinition.ITEM_DEFLECTION_SHIELD, "偏转护盾模型");
        builder.add(LangDefinition.ITEM_MAGNET, "磁铁模型");
        builder.add(LangDefinition.ITEM_FEATHER_ON_A_STICK, "羽毛钓竿");
        builder.add(LangDefinition.ITEM_DEED_OF_OWNERSHIP, "放生球");
        builder.add(LangDefinition.ITEM_DEED_OF_OWNERSHIP_DESC, "右键宠物,可以放生它");
        builder.add(LangDefinition.BLOCK_PET_BED_WHITE, "白色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_ORANGE, "橙色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_MAGENTA, "品红色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_LIGHT_BLUE, "淡蓝色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_YELLOW, "黄色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_LIME, "黄绿色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_PINK, "粉色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_GRAY, "灰色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_LIGHT_GRAY, "淡灰色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_CYAN, "青色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_PURPLE, "紫色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_BLUE, "蓝色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_BROWN, "棕色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_GREEN, "绿色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_RED, "红色宠物床");
        builder.add(LangDefinition.BLOCK_PET_BED_BLACK, "黑色宠物床");
        builder.add(LangDefinition.BLOCK_DRUM, "指挥鼓");
        builder.add(LangDefinition.BLOCK_WAYWARD_LANTERN, "迷途灯笼");
        builder.add(LangDefinition.MESSAGE_COMMAND_0, "%s 在游走");
        builder.add(LangDefinition.MESSAGE_COMMAND_1, "%s 在停留 ");
        builder.add(LangDefinition.MESSAGE_COMMAND_2, "%s 在跟随");
        builder.add(LangDefinition.MESSAGE_DRUM_COMMAND_0, "命令 %s 游走");
        builder.add(LangDefinition.MESSAGE_DRUM_COMMAND_1, "命令 %s 停留");
        builder.add(LangDefinition.MESSAGE_DRUM_COMMAND_2, "命令 %s 跟随");
        builder.add(LangDefinition.MESSAGE_RESPAWN, "%s 在它的床上重生了");
        builder.add(LangDefinition.MESSAGE_REMOVE_RESPAWN, "移除了 %s 重生记录的床");
        builder.add(LangDefinition.MESSAGE_GOODBYE, "%s 将不会重生，永别了……");
        builder.add(LangDefinition.MESSAGE_ENCHANTMENTS, "魔咒：");
        builder.add(LangDefinition.MESSAGE_SET_OWNER, "%s 现在是 %s 的所有者");
        builder.add(LangDefinition.MESSAGE_WAYWARD_LANTERN_RETURN, "%s 发现了附近的迷途灯笼");
        builder.add(LangDefinition.ENTITY_VILLAGER_ANIMAL_TAMER, "驯兽师");
        builder.add(LangDefinition.ENTITY_CHAIN_LIGHTNING, "闪电");
        builder.add(LangDefinition.ENTITY_RECALL_BALL, "召回宝盒");
        builder.add(LangDefinition.ENTITY_FEATHER, "羽毛");
        builder.add(LangDefinition.ENTITY_FOLLOWING_JUKEBOX, "漂浮唱片机");
        builder.add(LangDefinition.ENTITY_PSYCHIC_WALL, "心理墙");
        addEnchant(builder, ModEnchantments.SonicBoom, "冲击波", "冲击波可以击退敌人,每隔一段时间触发");
        addEnchant(builder, ModEnchantments.HEALTH_BOOST, "额外生命", "每升一级，宠物的生命值增加10点");
        addEnchant(builder, ModEnchantments.FIREPROOF, "防火", "火和岩浆造成的伤害对宠物无效");
        addEnchant(builder, ModEnchantments.IMMUNITY_FRAME, "免疫屏障", "每升一级会使宠物在受到伤害后增加1秒对伤害的免疫");
        addEnchant(builder, ModEnchantments.DEFLECTION, "偏转", "使宠物受到一个无形的盾牌保护使其免受伤害");
        addEnchant(builder, ModEnchantments.POISON_RESISTANCE, "抗毒", "使宠物对中毒效果免疫");
        addEnchant(builder, ModEnchantments.CHAIN_LIGHTNING, "连锁闪电", "在宠物攻击敌对生物时会召唤一个闪电对怪物造成伤害，每升一级会增加敌对生物被闪电击中的次数");
        addEnchant(builder, ModEnchantments.SPEEDSTER, "瞬速行者", "增加宠物的移动速度");
        addEnchant(builder, ModEnchantments.FROST_FANG, "冰霜利齿", "宠物在攻击时会对敌对生物减速并对会有冰冻效果");
        addEnchant(builder, ModEnchantments.MAGNETIC, "磁性", "使敌对生物吸引到宠物旁");
        addEnchant(builder, ModEnchantments.LINKED_INVENTORY, "物品栏关联", "宠物可以将拾的取物品放进到主人的背包中");
        addEnchant(builder, ModEnchantments.TOTAL_RECALL, "全面召回", "当宠物生命值低于 2 点时，宠物会进入召回球体并受到保护，直到主人释放");
        addEnchant(builder, ModEnchantments.HEALTH_SIPHON, "生命虹吸", "对宠物造成的任何伤害都会转移给它的主人");
        addEnchant(builder, ModEnchantments.BUBBLING, "冒泡", "会将宠物攻击的敌对生物困在向上漂浮的巨大气泡中");
        addEnchant(builder, ModEnchantments.SHEPHERD, "群集", "野生动物会被宠物吸引并跟随，每升一级会增加宠物可以被追随的数量");
        addEnchant(builder, ModEnchantments.AMPHIBIOUS, "两栖化", "宠物在陆地或水中不会被缺氧而死，在水中宠物不会漂浮到水面并且会增加移动速度");
        addEnchant(builder, ModEnchantments.VAMPIRE, "类吸血鬼", "为宠物治疗它所造成的伤害，每升一级增加伤害与治疗的百分比");
        addEnchant(builder, ModEnchantments.VOID_CLOUD, "虚空之云", "宠物受到虚空之云的保护，并不会掉入悬崖或落入虚空，而是虚空之云会将宠物托起并送回主人身旁");
        addEnchant(builder, ModEnchantments.INFAMY_CURSE, "恶名诅咒", "宠物可以使附近的任何敌对生物对它产生敌意");
        addEnchant(builder, ModEnchantments.SHADOW_HANDS, "暗影之手", "宠物使用黑暗魔法，用暗影之手攻击目标，每升一级会增加手的速度和手的数量");
        addEnchant(builder, ModEnchantments.DEFUSAL, "爆炸无效", "宠物可以使爆炸对地形和其他动物的伤害无效，每升一级增加无效的范围");
        addEnchant(builder, ModEnchantments.WARPING_BITE, "幻影移形", "宠物会随机地把目标敌对生物从身边传送走");
        addEnchant(builder, ModEnchantments.ORE_SCENTING, "矿物之味", "宠物可以用嗅觉发现矿石并提醒主人，该效果的等级决定发现的矿石的距离、数量和使用次数");
        addEnchant(builder, ModEnchantments.GLUTTONOUS, "贪吃", "宠物可以吃任何的食物并不受限制");
        addEnchant(builder, ModEnchantments.PSYCHIC_WALL, "心理墙", "在战斗时宠物会召唤心理墙来以提供掩护，该效果的等级决定了墙体的大小和效果的时长。");
        addEnchant(builder, ModEnchantments.INTIMIDATION, "恐吓", "宠物可以用可怕的外表吓跑敌对生物，该效果的等级决定了该效果的范围和使用次数");
        addEnchant(builder, ModEnchantments.BLIGHT_CURSE, "枯萎诅咒", "宠物周围的植物将会枯萎和死亡");
        addEnchant(builder, ModEnchantments.TETHERED_TELEPORT, "连接传送", "宠物将与主人一起传送，也可以跨越维度传送");
        addEnchant(builder, ModEnchantments.IMMATURITY_CURSE, "变小诅咒", "宠物出现时为宠物的小时候而且宠物的攻击伤害会降低");
        addEnchant(builder, ModEnchantments.BLAZING_PROTECTION, "火焰保护", "宠物每升一级会受到2个燃烧的棍的保护，燃烧的棍会击退并时攻击者燃烧");
        addEnchant(builder, ModEnchantments.HEALING_AURA, "治疗之息", "宠物会在偶然间治疗主人或在主人周围的其他宠物，该效果的等级决定了治疗的效果");
        addEnchant(builder, ModEnchantments.XP_Transfer, "经验转移", "宠物带有此附魔的项圈能收集周围的经验球,并转移到主人身上");
        addEnchant(builder, ModEnchantments.REJUVENATION, "恢复生命", "在宠物受伤时会吸收周围的经验球来治疗自己");
        addEnchant(builder, ModEnchantments.SHARE, "平摊", "宠物收到攻击时,会平摊伤害给周围的敌对生物");
        addEnchant(builder, ModEnchantments.NIGHT_VISION, "夜视", "当宠物在身边时,获得夜视效果");
        addEnchant(builder, ModEnchantments.INSIGHT, "洞察", "在暗处宠物会让周围的敌对生物高亮");
        addEnchant(builder, ModEnchantments.CHAOS, "混乱之脑", "宠物被攻击时，使攻击者获得混乱buff，攻击位于半径10格内的其他怪物");
        addEnchant(builder, ModEnchantments.PARALYSIS, "麻痹", "宠物被攻击时，使攻击者无法移动、跳跃或攻击几秒钟");
        addEnchant(builder, ModEnchantments.TOUGH, "稳固", "增加宠物的防御和抗击退");
        addEnchant(builder, ModEnchantments.VIOLENT, "暴力", "宠物攻击的生物会获得一些debuff");
        builder.add(LangDefinition.SOUND_SUBTITLE_COLLAR_TAG, "已装备项圈标签");
        builder.add(LangDefinition.SOUND_SUBTITLE_MAGNET_LOOP, "磁铁：呲呲");
        builder.add(LangDefinition.SOUND_SUBTITLE_CHAIN_LIGHTNING, "闪电：电击");
        builder.add(LangDefinition.SOUND_SUBTITLE_GIANT_BUBBLE_INFLATE, "大泡泡：膨胀");
        builder.add(LangDefinition.SOUND_SUBTITLE_GIANT_BUBBLE_POP, "大泡泡：爆炸");
        builder.add(LangDefinition.SOUND_SUBTITLE_PET_BED_USES, "调整过的宠物床");
        builder.add(LangDefinition.SOUND_SUBTITLE_DRUM, "指挥鼓鼓点");
        builder.add(LangDefinition.SOUND_SUBTITLE_PSYCHIC_WALL, "心理墙的嗡嗡声");
        builder.add(LangDefinition.SOUND_SUBTITLE_PSYCHIC_WALL_DEFLECT, "心理墙的偏移");
        builder.add(LangDefinition.SOUND_SUBTITLE_BLAZING_PROTECTION, "燃烧的棍消失了");
        builder.add(LangDefinition.JADE_COLLAR_TAG, "项圈描述");
        builder.add(LangDefinition.effect("drunk"), "混乱");
        builder.add(LangDefinition.NOTIF_FRIENDLYFIRE_PROTECTED, "这只%s受保护。潜行状态可绕过保护。");
        builder.add(LangDefinition.has_pet_bed_at_pos, "已绑定宠物床( %s )");
        builder.add(PHItemRegistry.NET_LAUNCHER_ITEM, "生物捕捉发射器");
        builder.add(PHItemRegistry.NET_ITEM, "生物球");
        builder.add(PHItemRegistry.NET_HAS_ITEM, "生物球");
        builder.add(LangDefinition.capturing_text, "捕捉");
        builder.add(LangDefinition.release_text, "释放");
        builder.add(LangDefinition.health_text, "生命值");
        builder.add(LangDefinition.no_net_entity_text, "没有可以释放的生物球");
        builder.add(LangDefinition.net_launcher_tip, "[按住shift然后右击,可以切换释放和捕捉状态]");
        builder.add(LangDefinition.net_launcher_default_only_tamable, "默认只能捕捉可驯服的生物,可以在配置文件修改");
        builder.add(LangDefinition.mobcatcherOnlyTamableAnimal_conf, "生物球只能捕捉可驯服的生物");
        builder.add(LangDefinition.mobcatcherOnlyTamableAnimal_conf_tooltip, "设置为否可以捕捉所有生物");
        builder.add(LangDefinition.mobcatcherBlacklist_conf, "生物球可捕捉黑名单");
        builder.add(LangDefinition.mobcatcherBlacklist_conf_tooltip, "生物球不能捕捉的生物");


        builder.add(LangDefinition.network_failed, "网络错误");
        builder.add(LangDefinition.TOOLTIP_DRUM_DESC, "[右击切换指令模式,对32格内自己的宠物生效,可用红石信号触发]");
        builder.add(LangDefinition.TOOLTIP_WAYWARD_LANTERN_DESC, "[放置在身边,远离而被卸载的宠物会被传送回灯笼旁]");

        // —— 游戏内设置界面（client/gui/PetHomeConfigScreen）文案，键名与 1.20.1 一致 ——
        builder.add(LangDefinition.GUI_TITLE, "驯养革新 · 设置");
        builder.add(LangDefinition.GUI_SUBTITLE, "修改即时保存到 config/pet_home.toml");
        builder.add(LangDefinition.GUI_RESET, "重置");
        builder.add(LangDefinition.GUI_ON, "开启");
        builder.add(LangDefinition.GUI_OFF, "关闭");
        builder.add(LangDefinition.GUI_CAT_FRIENDLY_NAME, "友好保护");
        builder.add(LangDefinition.GUI_CAT_FRIENDLY_DESC, "宠物与主人、宠物之间、队伍的保护规则");
        builder.add(LangDefinition.GUI_CAT_GENERAL_NAME, "通用功能");
        builder.add(LangDefinition.GUI_CAT_GENERAL_DESC, "宠物床、指令、生物球等功能开关");
        builder.add(LangDefinition.GUI_CAT_TAMEABLE_NAME, "驯服扩展");
        builder.add(LangDefinition.GUI_CAT_TAMEABLE_DESC, "美西螈、狐狸、青蛙、马、兔子的驯服开关");
        builder.add(LangDefinition.GUI_CAT_LOOT_NAME, "战利品概率");
        builder.add(LangDefinition.GUI_CAT_LOOT_DESC, "各结构宝箱中附魔书与特殊物品的出现概率");
        builder.add(LangDefinition.GUI_CAT_ENCHANTS_NAME, "附魔开关");
        builder.add(LangDefinition.GUI_CAT_ENCHANTS_DESC, "逐项启用/禁用各宠物附魔");
        builder.add(LangDefinition.GUI_F_PROTECT_OWNER, "主人不能伤害宠物");
        builder.add(LangDefinition.GUI_F_PROTECT_OWNER_DESC, "主人攻击自己的宠物时无效");
        builder.add(LangDefinition.GUI_F_PROTECT_PETS, "宠物之间不能互相伤害");
        builder.add(LangDefinition.GUI_F_PROTECT_PETS_DESC, "宠物攻击其他玩家的宠物时无效");
        builder.add(LangDefinition.GUI_F_PROTECT_CHILDREN, "保护幼年生物");
        builder.add(LangDefinition.GUI_F_PROTECT_CHILDREN_DESC, "幼年生物受到保护");
        builder.add(LangDefinition.GUI_F_REFLECT_DAMAGE, "反伤攻击者");
        builder.add(LangDefinition.GUI_F_REFLECT_DAMAGE_DESC, "保护触发时反弹伤害给攻击者");
        builder.add(LangDefinition.GUI_F_DISPLAY_WARNING, "显示受保护提示");
        builder.add(LangDefinition.GUI_F_DISPLAY_WARNING_DESC, "攻击受保护宠物时显示提示信息");
        builder.add(LangDefinition.GUI_F_PROTECT_TEAM, "保护同队成员");
        builder.add(LangDefinition.GUI_F_PROTECT_TEAM_DESC, "同一队伍的生物互相保护");
        builder.add(LangDefinition.GUI_F_RESPECT_TEAM, "遵守队伍规则");
        builder.add(LangDefinition.GUI_F_RESPECT_TEAM_DESC, "按照队伍规则决定保护行为");
        builder.add(LangDefinition.GUI_F_CAN_HURT_PET_ITEMS, "可伤害宠物的物品");
        builder.add(LangDefinition.GUI_F_CAN_HURT_PET_ITEMS_DESC, "逗号分隔的物品 ID，持有这些物品时可以伤害宠物（如 minecraft:egg）");
        builder.add(LangDefinition.GUI_F_CAN_HURT_ALL_ITEMS, "总能造成伤害的物品");
        builder.add(LangDefinition.GUI_F_CAN_HURT_ALL_ITEMS_DESC, "逗号分隔的物品 ID，持有这些物品时无视保护");
        builder.add(LangDefinition.GUI_F_NO_PROTECTION, "不受保护的生物");
        builder.add(LangDefinition.GUI_F_NO_PROTECTION_DESC, "逗号分隔的生物 ID，这些生物不受保护规则限制");
        builder.add(LangDefinition.GUI_F_EXTRA_PROTECTED, "额外受保护的生物");
        builder.add(LangDefinition.GUI_F_EXTRA_PROTECTED_DESC, "逗号分隔的生物 ID，这些生物也纳入保护");
        builder.add(LangDefinition.GUI_F_PLAYER_PROTECTED, "玩家不能伤害的生物");
        builder.add(LangDefinition.GUI_F_PLAYER_PROTECTED_DESC, "逗号分隔的生物 ID，玩家无法伤害这些生物");
        builder.add(LangDefinition.GUI_G_ROTTEN_APPLE, "烂苹果转化");
        builder.add(LangDefinition.GUI_G_ROTTEN_APPLE_DESC, "苹果掉落后会腐烂成烂苹果");
        builder.add(LangDefinition.GUI_G_PET_BED_RESPAWN, "宠物床重生");
        builder.add(LangDefinition.GUI_G_PET_BED_RESPAWN_DESC, "宠物死亡后第二天在绑定的宠物床重生");
        builder.add(LangDefinition.GUI_G_RABBITS_RAVAGERS, "兔子吓掠夺兽");
        builder.add(LangDefinition.GUI_G_RABBITS_RAVAGERS_DESC, "还原旧版：掠夺兽害怕兔子");
        builder.add(LangDefinition.GUI_G_TRINARY_COMMAND, "三态指令系统");
        builder.add(LangDefinition.GUI_G_TRINARY_COMMAND_DESC, "右键宠物切换 游走/停留/跟随");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY, "宠物信息面板");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY_DESC, "准星对准自己的宠物时显示其信息（指令状态/宠物床/生命值/项圈附魔）");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY_REQUIRE_SHIFT, "宠物信息面板（需要按住 Shift）");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY_REQUIRE_SHIFT_DESC, "仅按住 Shift 时显示宠物信息面板（默认：准星对准自己的宠物即显示）");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY_IGNORE_JADE, "宠物信息面板（无视 Jade）");
        builder.add(LangDefinition.GUI_G_PET_INFO_OVERLAY_IGNORE_JADE_DESC, "安装 Jade 时仍启用宠物信息面板");
        builder.add(LangDefinition.GUI_G_PETSTORE_WEIGHT, "宠物商店生成权重");
        builder.add(LangDefinition.GUI_G_PETSTORE_WEIGHT_DESC, "宠物商店结构在村庄中的生成权重（0 为禁用）");
        builder.add(LangDefinition.GUI_G_MOB_TAMABLE_ONLY, "生物球只捕捉可驯服生物");
        builder.add(LangDefinition.GUI_G_MOB_TAMABLE_ONLY_DESC, "关闭后生物球可以捕捉所有生物");
        builder.add(LangDefinition.GUI_G_MOB_BLACKLIST, "生物球捕捉黑名单");
        builder.add(LangDefinition.GUI_G_MOB_BLACKLIST_DESC, "逗号分隔的生物 ID，这些生物不能被生物球捕捉");
        builder.add(LangDefinition.GUI_T_AXOLOTL, "驯服美西螈");
        builder.add(LangDefinition.GUI_T_AXOLOTL_DESC, "用热带鱼驯服美西螈");
        builder.add(LangDefinition.GUI_T_FOX, "驯服狐狸");
        builder.add(LangDefinition.GUI_T_FOX_DESC, "用甜浆果驯服狐狸");
        builder.add(LangDefinition.GUI_T_FROG, "驯服青蛙");
        builder.add(LangDefinition.GUI_T_FROG_DESC, "用蜘蛛眼驯服青蛙");
        builder.add(LangDefinition.GUI_T_HORSE, "驯服马");
        builder.add(LangDefinition.GUI_T_HORSE_DESC, "马可以像狼一样被驯服");
        builder.add(LangDefinition.GUI_T_RABBIT, "驯服兔子");
        builder.add(LangDefinition.GUI_T_RABBIT_DESC, "用胡萝卜驯服兔子");
        builder.add(LangDefinition.GUI_L_CURSE_LOOT_ONLY, "诅咒附魔仅战利品");
        builder.add(LangDefinition.GUI_L_CURSE_LOOT_ONLY_DESC, "诅咒类附魔只能从宝箱获得");
        builder.add(LangDefinition.GUI_L_SINISTER_CARROT_DESC, "林地府邸宝箱出现阴恶胡萝卜的概率");
        builder.add(LangDefinition.GUI_L_BUBBLING_DESC, "埋藏的宝藏出现冒泡附魔书的概率");
        builder.add(LangDefinition.GUI_L_VAMPIRISM_DESC, "林地府邸出现类吸血鬼附魔书的概率");
        builder.add(LangDefinition.GUI_L_VOID_CLOUD_DESC, "末地城出现虚空之云附魔书的概率");
        builder.add(LangDefinition.GUI_L_ORE_SCENTING_DESC, "废弃矿井出现矿物之味附魔书的概率");
        builder.add(LangDefinition.GUI_L_BLAZING_DESC, "下界要塞出现火焰保护附魔书的概率");
        builder.add(LangDefinition.GUI_L_SHARE_DESC, "末地城出现平摊附魔书的概率");
        builder.add(LangDefinition.GUI_L_SONIC_BOOM_DESC, "林地府邸出现冲击波附魔书的概率");
        builder.add(LangDefinition.GUI_L_PARALYSIS_DESC, "矿井/沙漠神殿/初始箱出现麻痹附魔书的概率");
        builder.add(LangDefinition.GUI_L_TOUGH_DESC, "废弃矿井出现稳固附魔书的概率");
        addPetCompass(builder);
    }


    private void addEnchant(TranslationBuilder builder, ResourceKey<Enchantment> enchantmentResourceKey, String name, String desc) {
        String base = LangDefinition.enchantment(enchantmentResourceKey.location().getPath());
        builder.add(base, name);
        builder.add(base + ".desc", desc);
    }

    private void addPetCompass(FabricLanguageProvider.TranslationBuilder builder) {
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_DESC, "右键打开宠物列表（传送至宠物 / 召回宠物）");
        builder.add(LangDefinition.ITEM_PET_COMPASS, "宠物罗盘");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_UNBOUND, "右键自己驯服的宠物进行绑定");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_BOUND, "已绑定：%s");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_DISTANCE, "距离：%s 米");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_LAST_KNOWN, "宠物不在已加载区块，指向最后已知位置");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_WRONG_DIM, "宠物在其他维度：%s");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_WAITING_LANTERN, "宠物在迷途灯笼处等待召回");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_WAITING_RESPAWN, "宠物已死亡，等待宠物床复活");
        builder.add(LangDefinition.TOOLTIP_PET_COMPASS_UNBIND_HINT, "潜行 + 右键空气解绑");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_TITLE, "宠物罗盘");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_EMPTY, "还没有可追踪的宠物");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_POSITION, "位置：");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_LAST_KNOWN_POS, "最后已知：");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DISTANCE, "距离：%s 米");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DIM_OVERWORLD, "主世界");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DIM_THE_NETHER, "下界");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DIM_THE_END, "末地");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_LOADED, "状态：已加载");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_NOT_LOADED, "状态：未加载");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_WRONG_DIM, "状态：在其他维度");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_STATUS_DEAD, "状态：已死亡，等待宠物床复活");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_BUTTON_TP, "传送至宠物");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_BUTTON_RECALL, "召回");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DISABLED, "宠物罗盘功能已在配置中关闭");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_DEAD_WAIT_RESPAWN, "该宠物已死亡，正在等待宠物床复活");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_NOT_LOADED_CONFIRM, "宠物当前未加载，将传送到最后已知位置");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_TELEPORTED, "已传送到宠物身边");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_RECALLED, "%s 已召回至你身边");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_RECALL_STARTED, "正在寻找宠物，请稍候……");
        builder.add(LangDefinition.MESSAGE_PET_COMPASS_RECALL_FAILED, "未能找到宠物，请稍后重试");
        builder.add(LangDefinition.GUI_G_PET_COMPASS, "宠物罗盘");
        builder.add(LangDefinition.GUI_G_PET_COMPASS_DESC, "宠物罗盘功能总开关");
        builder.add(LangDefinition.GUI_G_PET_COMPASS_TP_P, "传送玩家到宠物");
        builder.add(LangDefinition.GUI_G_PET_COMPASS_TP_P_DESC, "允许将玩家传送到宠物所在位置");
        builder.add(LangDefinition.GUI_G_PET_COMPASS_TP_R, "召回宠物到玩家");
        builder.add(LangDefinition.GUI_G_PET_COMPASS_TP_R_DESC, "允许将宠物召回至玩家身边");
    }
}
