plugins {
    id("idea")
}

allprojects {


repositories {
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = "Ladysnake"
        url = "https://maven.ladysnake.org/releases/"
    }
  maven {
         name = 'ParchmentMC'
         url = 'https://maven.parchmentmc.org'
     }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}


}