# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
systemProp.socks.proxyHost=127.0.0.1
systemProp.socks.proxyPort=7897
systemProp.http.nonProxyHosts=developer.huawei.com|maven.aliyun.com|mirrors.tencent.com|192.168.*